### PR TITLE
Add lmfit to list of requirements for hexrd

### PR DESCRIPTION
**Pull request by psavery**
It is required to use WPPF.

The version is set at 1.0.0 for reasons mentioned in hexrd/hexrd#99.

Fixes: #99

I think I might need to add it to the [meta.yaml](https://github.com/HEXRD/hexrd/blob/master/conda.recipe/meta.yaml) for conda as well.

### CODE REVIEW

**Comment by cjh1** [comment]
Yes lets add it to the conda recipe as well.

**Review by cjh1 — APPROVED** [review]

**Comment by psavery** [comment]
Looks like it broke the conda package :slightly_frowning_face:

**Comment by psavery** [comment]
This works in the command line, though:

```bash
conda install -c conda-forge lmfit==1.0.0
```

**Comment by joelvbernier** [comment]
Hmmm.  We can probably find a replacement if we have to, right @saransh13 ?  Is this straight up Levenberg-Marquadt?

**Comment by psavery** [comment]
@cjh1 Do we need to just get it to check `conda-forge` for the runtime dependencies as well?

**Comment by cjh1** [comment]
I think [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html) has Levenberg-Marquadt if that is all that is needed. Might be nice to use it if its not too much trouble, as its already a dep. Otherwise, I can take a look at the packaging issue.

**Comment by saransh13** [comment]
`lmfit` just wraps the `scipy` routines. However, theres a parameter class that `lmfit` introduces which is currently being used.

**Comment by cjh1** [comment]
@saransh13 Is [this](https://github.com/lmfit/lmfit-py/blob/master/lmfit/parameter.py) the class you are talking about? Would be possible to call scipy directly?

**Comment by saransh13** [comment]
@cjh1 yep thats the class. It should be possible, but will probably require a little time to update everything.
I've also have a PR which should eliminate the requirement for `1.0.0` and we can safely use the latest `1.0.1`.
This should resolve the broken conda package for the time being.

**Comment by cjh1** [comment]
@saransh13 I think we need to make come changes to the packaging for this, I will take a look.

**Comment by psavery** [comment]
@cjh1 Should we put the anaconda channel first to prefer anaconda over conda-forge?

The mac build failed because of something to do with libopenblas. But I think preferring anaconda will eliminate libopenblas usage anyways.

**Comment by cjh1** [comment]
@psavery I think you might be right, I am looking at it now ...

**Comment by cjh1** [comment]
Finally packaged! :fireworks:

**Review by cjh1 — APPROVED** [review]

**Comment by psavery** [comment]
Once #108 gets merged, we can potentially remove the version number from lmfit.

**Comment by cjh1** [comment]
@psavery I updated it to relax the version ...

**Pull request merged**
