### PR TITLE
Restore extend_path call for pkgutil-style namespace package

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@joelvbernier This restores the part that is actually needed! Note there is another issue with dev install that I will push a PR for in hexrdgui. For now if you want to test this, just install hexrdgui first then hexrd ... as in:

```
pip install -e hexrdgui
pip install -e hexrd
```

**Review by psavery — APPROVED** [review]
LGTM

**Comment by cjh1** [comment]
@joelvbernier I tested this with the conda dev install and everything works as expected.

**Comment by joelvbernier** [comment]
@cjh1 -- can you post the conda dev instructions alongside the `pip -e` method?  I haven't used `conda develop` much...

**Comment by psavery** [comment]
> @cjh1 -- can you post the conda dev instructions alongside the `pip -e` method? I haven't used `conda develop` much...

I think he meant he tested it using the conda dev env instructions in the README

**Comment by joelvbernier** [comment]
ah -- I see.  I know that `conda develop` exists, but I haven't used it...

**Comment by cjh1** [comment]
@joelvbernier @psavery I also testing the pip dev environment ( documented in the README ), this also works.

**Pull request merged**
