### PR TITLE
fix error in fractional occupancy cases while reading cif file.

### PR DESCRIPTION
**Pull request by saransh13**
Same as description.

### CODE REVIEW

**Comment by saransh13** [comment]
@psavery it seems like PEP8 is not happy with the bare except. Do you know of a better way to handle this part of the code?

**Comment by psavery** [comment]
It wants you to specify the type of exception. In this case, it should only ever raise a `ValueError`, so you could do `except ValueError:`.

If you want to catch every possible exception, you can still do `except Exception`, which catches them all.

**Comment by ZackAttack614** [comment]
[This](https://github.com/HEXRD/hexrd/blob/cif-fix-refactor/hexrd/material/material.py#L710-L716) may be a bit cleaner, if I am understanding the use case well enough:

```python
            occ = []
            for p in cifdata[occ_U[0]]:
                v = p.split('(')[0]

                occ.append(np.float64(v) if v.isnumeric() else 1.0)

            atompos.append(np.asarray(occ))
```

**Comment by ZackAttack614** [comment]
@saransh13 I would like to close out of our dangling PRs before we can begin the v1.0 migration. Has there been activity on this? If not, I would like to propose closing it or wrapping up work to merge it in this week.

**Comment by saransh13** [comment]
@ZackAttack614 I will update the PR later today.

**Comment by saransh13** [comment]
@ZackAttack614 Your proposed changes fails for a simple test case with fractional occupancy. I prefer to keep the original code which was giving the right results. We can come back and simplify the code in a future PR.

**Comment by ZackAttack614** [comment]
@saransh13 no problem at all, thanks so much for prioritizing this!

**Comment by saransh13** [comment]
@ZackAttack614 Do you mind reviewing the PR? @psavery is on conference travel this week

**Review by ZackAttack614 — APPROVED** [review]
This looks all right, though going forward we'll be more rigid about making sure changes are covered by unit tests, indicated by the Codecov bot. @saransh13 if possible, could you add some unit test coverage for this function before merging? I'll approve this regardless, and if need be we can come back to that tomorrow when Kevin Lewis is around.

**Comment by saransh13** [comment]
Yeah, I'd need some help from @kevindlewis23 to include it in the unit test. I have the data files and script that we need for that though. I'll merge this in the meantime since this is an important bug fix, and add the unit test as a future PR.

**Pull request merged**
