### PR TITLE
Chunk stats

### PR DESCRIPTION
**Pull request by donald-e-boyce**
This updates the imageseries.stats.median() function to use chunks and return an intermediate image at each point, allowing the calling function to update a progress bar. I will follow up with another request applying these changes to other functions such average, max or percentile. Here is an example of the usage:

```python
import numpy as np

from hexrd import imageseries


stats = imageseries.stats

a = np.ones((50, 10, 6))
for i in range(a.shape[1]): # set values by row
    a[:,i,:] = i
ims = imageseries.open(None, 'array', data=a)


def run_chunk(ims, nchunk):
    img = np.zeros(ims.shape)
    for i in range(nchunk):
        img = stats.median(ims, chunk=(i, nchunk, img))
        print("%d/%d\n" % (i, nchunk), img)
    return img
```

### CODE REVIEW

**Comment by donald-e-boyce** [comment]
The stats module looks good now. All functions can be called with the chunk argument. The module documentation explains the chunking interface.

**Comment by psavery** [comment]
@donald-e-boyce So, I started trying this out in hexrdgui, and I think it is working. However, I noticed that there seem to be some performance hits, and I wonder if we might be able to do anything to make these functions run faster.

I wrote a script to perform some timings, and it is attached below. I'm timing our `multiruby2_6_ff1_000048-cachefile.npz` file (~1.3 MB), and I can send it to you if you need it.

For the `max` function:
* master branch: 16.53 seconds
* this branch with `chunk=None`: 76.07 seconds
* this branch with 51 chunks: 817.68 seconds

This could be problematic, as it might make the loading time a lot longer.

[test.py.gz](https://github.com/HEXRD/hexrd/files/4225816/test.py.gz)

**Comment by donald-e-boyce** [comment]
OK, I'll check it out.

**Comment by donald-e-boyce** [comment]
I pushed up a new commit. There was a logging statement I got rid of, and I dropped use of the processed imageseries rectangle. There was also a genuine bug that reset the number of frames to the length of the imageseries, even if a smaller number was specified. I don't see how that affected the all-frames case, but somehow it seemed to speed up after that.

Still, it looks like there is a cost to chunking.  Below are timings for the stats.max function for the frame-cache used above. I think what is happening is that I set up the chunking to chunk by rows. That is because the median function was my model, and you need all the frames to compute the median, but you can compute the median row by row. For the average, max and min, you can break it into frames and combine the results later. In fact the max() function (previously) only ever had two frames loaded at a time, the running max image and the current frame. 

Now, to compute the median over several rows for a large number of frames, you end up loading all the frames anyway because of the way imageseries gets the frames---to get a subset of rows, you have to get the full frame first.  For a frame-cache, all images are available in memory, but as sparse matrices, so there is also some overhead converting to a full image. Likewise for HDF5.

>  testing stats.max
> 
>  ===== 0 chunks, 100 frames
> elapsed time:  3.01 seconds
> 
>  ===== 1 chunks, 100 frames
>  0/1 
> done
> elapsed time:  2.95 seconds
> 
>  ===== 10 chunks, 100 frames
>  0/10 
> .........done
> elapsed time:  5.7 seconds
> 
>  ===== 50 chunks, 100 frames
>  0/50 
> ......... 10/50 
> ......... 20/50 
> ......... 30/50 
> ......... 40/50 
> .........done
> elapsed time:  18.35 seconds
> 
>  ===== 0 chunks, 1441 frames
> elapsed time:  70.93 seconds
> 
>  ===== 20 chunks, 1441 frames
>  0/20 
> ......... 10/20 
> .........done
> elapsed time:  136.74 seconds
> 
>  ===== 50 chunks, 1441 frames
>  0/50 
> ......... 10/50 
> ......... 20/50 
> ......... 30/50 
> ......... 40/50 
> .........done
> elapsed time:  268.78 seconds
>

**Comment by donald-e-boyce** [comment]
Here is the test script I've been using.

**Comment by psavery** [comment]
@donald-e-boyce I don't see an attached script. Could you try attaching it again?

Here are the updated timings from my script, using the latest from this branch:

For the `max` function on `multiruby2_6_ff1_000048-cachefile.npz`:
* master branch: 16.46 seconds
* this branch with `chunk=None`: 34.80 seconds
* this branch with 51 chunks: 109.66 seconds

Also note that for this `multiruby` example, when we load it in hexrdgui, there are two cache files to load (not just one, as is being done in this test), and more aggregations might need to be performed for the dark images.

**Comment by donald-e-boyce** [comment]
I did some profiling on this. It looks like most of the overhead is indeed loading the frames. In fact, a significant part of that is numpy.zeros() function, which is called in the toarray() method of the scipy.sparse.csr_matrix (compressed sparse row format). So in pulling the frame, much of the work is writing zeros for the full matrix.

**Comment by donald-e-boyce** [comment]
I updated the stats module creating an iterable for each function, as you suggested. It is much cleaner and performs much better. Each function has a corresponding iterable. For example, to find the max, you can either use stats.max() as before or stats.max_iter(), which returns and iterable for use with the progress bar. See module documentation.

**Comment by psavery** [comment]
@donald-e-boyce I'm still working on this, but it has been working very well so far, Don. Thank you very much!

**Comment by psavery** [comment]
@donald-e-boyce This has been working great, Don. Thank you for the work!

I have one request right now, though. It looks like if you pass in `nchunk=1` and `nframes=1`, you get an exception like below. Could you modify the code so that we don't get an exception if `nchunk=1` and `nframes=1`?
```python
Traceback (most recent call last):
  File "test.py", line 145, in <module>
    time_all(nframes, nchunks)
  File "test.py", line 35, in time_all
    time_iter("max iterable", stats.max_iter, ims, nc, nf)
  File "test.py", line 94, in time_iter
    for i, img in enumerate(op(ims, nchunk, nframes=nframes)):
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/imageseries/stats.py", line 48, in max_iter
    stop = stops[s0]
```

**Comment by psavery** [comment]
Or maybe just a different exception. I realize that we could also just change it on our end to just return the image if `nframes=1` as well...

**Comment by donald-e-boyce** [comment]
I fixed it. I am just checking it. I will push shortly.

**Comment by psavery** [comment]
@donald-e-boyce Great! Thank you don. This simplifies things a little bit on our part.

**Comment by psavery** [comment]
I think this PR is ready for merging for me, if it is ready for you guys.

@donald-e-boyce @joelvbernier

**Comment by cjh1** [comment]
@donald-e-boyce @joelvbernier If this one is ready to merge, lets do it, so we merge the hexrdgui portion.

**Pull request merged**
