### PR TITLE
updated config to use working_dir consistently

### PR DESCRIPTION
**Pull request by donald-e-boyce**
To address this, I added a static method in the base config class that checks filename "correctness." If the filename is an absolute path, that is what gets used. If it is a relative path, then the working_dir is prepended. Finally, if a file exists for that path, then that is returned. Otherwise, IOError is raised.

I applied this to instrument config file and to the imageseries files loaded in the image_dict.

### CODE REVIEW

**Comment by donald-e-boyce** [comment]
Fixed pep 8 error. Also note this pull request refers to Issue #80 .

**Comment by joelvbernier** [comment]
@donald-e-boyce and @cjh1 -- want to look into why the checks failed on this?

**Comment by joelvbernier** [comment]
@donald-e-boyce , looks ok, @cjh1 is on the cause of the failed checks.  Regarding that, @cjh1 what is the meaning of "canceled" vs. "failing" checks?

**Comment by joelvbernier** [comment]
As the failed tests are unrelated, going to get this merged.

**Comment by cjh1** [comment]
@joelvbernier The distinction between "canceled" and "failing" checks is the following. The checks on Windows "failed", because of the numpy/setuptools issue, this causes the other platforms to be "cancelled", as the CI is setup so everything should pass, so if something fails it cancels everything ...

**Pull request merged**
