### PR TITLE
Replace previously archived functions

### PR DESCRIPTION
**Pull request by ZackAttack614**
This PR will replace some previously archived functions from the `hexrd/material/crystallography.py` script in the current pre-release.

### CODE REVIEW

**Review by psavery — APPROVED** [review]
Thanks Zack. I'm assuming the contents of the functions did not change at all? If not, looks good to me!

**Comment by ZackAttack614** [comment]
Yep, it's identical to the code that was previously archived. Thanks, Patrick!

**Comment by saransh13** [comment]
Any reason we are re-merging these archived functions? There are duplicates in the codebase now for the structure factor calculator in `hexrd.wppf.xtal._calcxrsf`.

**Comment by ZackAttack614** [comment]
@saransh13 Thanks for pointing this out. This change was originally a part of a non-final change identifying code for removal. We have replaced it to prevent others' workflows from failing in pre-release.

This will be reevaluated when the whole community will weigh in on a duplicate code strategy. More to come on that soon.

**Pull request merged**
