### PR TITLE
Updates to support state files in hexrdgui

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by psavery** [comment]
This seems to be working for the pieces in hexrd/hexrdgui#1039. In that PR, we have state saving for the following:

1. Materials
2. Instrument
3. Hexrdgui config
4. Masks

We will likely need some small changes to hexrd to get image data state saving to work as well. Perhaps we can do that in a separate PR, and just get these things merged.

**Comment by cjh1** [comment]
@joelvbernier Can you take a look at our changes with a view to what might cause problems with your scripting ...

**Comment by psavery** [comment]
> Hello @cjh1! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
> * In the file [`hexrd/imageseries/load/hdf5.py`](https://github.com/HEXRD/hexrd/blob/b5c607a3f29f4a0765f63ef87c790546839c5382/hexrd/imageseries/load/hdf5.py):
> 
> > [Line 18:80](https://github.com/HEXRD/hexrd/blob/b5c607a3f29f4a0765f63ef87c790546839c5382/hexrd/imageseries/load/hdf5.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

Odd, that line is only 69 characters long. I'll just ignore it.

**Comment by psavery** [comment]
A commit was just added that allows for saving/loading data in a state file in HEXRD/hexrdgui#1039.

**Review by joelvbernier — APPROVED** [review]

**Pull request merged**
