### PR TITLE
pass charge value to _set_atomdata.

### PR DESCRIPTION
**Pull request by saransh13**
ability to charge as part of _set_atomdata function in Material class. This will be utilized for PR https://github.com/HEXRD/hexrdgui/pull/973 in the GUI.

### CODE REVIEW

**Review by psavery — APPROVED** [review]
LGTM

**Comment by psavery** [comment]
When we merge this, we need to also merge hexrd/hexrdgui#973 right away, so that the GUI doesn't break...

**Comment by joelvbernier** [comment]
Well merge this one when we are ready to stage a new GUI release including hexrd/hexrdgui#513, yeah?  Or are things broken in the gui without this @saransh13?

**Comment by saransh13** [comment]
The current GUI works. But if we merge this one, then the GUI code would
need to be updated. I think Patrick already has a PR for that.

**Comment by psavery** [comment]
Yeah, we currently need to merge this one before we merge hexrd/hexrdgui#973. That can wait until after the release if you prefer, though, @joelvbernier

**Comment by joelvbernier** [comment]
Question: it seems like if I merge this, then I should tag at 0.8.10 and point the corresponding hexrdgui (post merging hexrd/hexrdgui#973) to require hexrd >= 0.8.10, yes?

**Pull request merged**
