### PR TITLE
[WIP] DBG check conda-forge sklearn 0.24.2 package

### PR DESCRIPTION
**Pull request by glemaitre**
Related to https://github.com/scikit-learn/scikit-learn/issues/20140

Checking if the conda-forge binary is failing

### CODE REVIEW

**Comment by glemaitre** [comment]
@psavery we can attend to only install scikit-learn at first and see if it fails. Otherwise, it means that this is an interaction with the `anaconda` distribution as well.

**Comment by psavery** [comment]
@glemaitre It looks like installing from `conda-forge` worked. So it is indeed a problem specific to the `anaconda` distribution.

**Comment by glemaitre** [comment]
Yep. I am interested to know if it is related to install `anaconda` and `scikit-learn` or just `scikit-learn`. It would be easier to provide a bit more inside to anaconda.

**Comment by glemaitre** [comment]
So `conda install scikit-learn` is enough to reproduce the problem. I am unsure where we can report this thought :). Maybe @ogrisel has an idea.

**Comment by psavery** [comment]
@glemaitre Thank you for looking into this. We changed our project to now use dependencies from `conda-forge` instead of `anaconda`. That fixed the `scikit-learn` issues we were having. So I think we can close this PR.

**Pull request closed without merging**
