### PR TITLE
WPPF update

### PR DESCRIPTION
**Pull request by saransh13**
Removed the dependence of mixing factor on a polynomial in theta. Instead this is replaced by the mixing factor, η, given in P. Thompson, D.E. Cox & J.B. Hastings, J. Appl. Cryst.,20,79-83, 1987. This also changes the convention a little bit where  η=1 is pure Lorentzian and  η=0 is pure Gaussian. Leads a way. more stable optimization behavior.

### CODE REVIEW

**Comment by joelvbernier** [comment]
@saransh13 -- does [this ](https://github.com/HEXRD/hexrd/pull/164/commits/1b2c1dc0f2268b741d7c8250ac2922d249a84f59)commit store/set the exclusions upon save/load?

**Comment by saransh13** [comment]
@joelvbernier just submitted a separate PR which deals with that.

**Comment by joelvbernier** [comment]
Is this ready for prime time?  You've tested it?

**Comment by joelvbernier** [comment]
(still showing as a draft PR)

**Comment by saransh13** [comment]
Removing draft status. Should work now. Just one point to mention is that this will involve a small change in `hexrdGUI` package too. I'll be submitting a PR for that as well.

**Comment by joelvbernier** [comment]
Ok, we should have that one staged so that things aren't broken too long, and make a note of this merge in that merge commit as well.

**Review by joelvbernier — APPROVED** [review]

**Comment by saransh13** [comment]
@joelvbernier -- asked for your review on the corresponding changes in hexrdgui. Submitted that earlier today. Will merge after those changes are approved.

**Pull request merged**
