### PR TITLE
Lmfit fix

### PR DESCRIPTION
**Pull request by saransh13**
There was a change in one of the keywords to the `lmfit.Minimizer` class in release `1.0.1`. 
Fixing the keyword seems to produce identical results to `v1.0.0`. 
This should resolve the conda package being broken in PR #105

### CODE REVIEW

**Comment by cjh1** [comment]
@saransh13 I don't this this will help. However, I can look at fixed the packaging in #105

**Review by joelvbernier — COMMENTED** [review]
Didn't you commit the material and symbols changes in #107 ?

**Review by cjh1 — APPROVED** [review]
This looks good to me, @saransh13 Looks like @joelvbernier has a question?

**Comment by saransh13** [comment]
@joelvbernier Yep, I think so. This change just made `lmfit1.0.1`work with WPPF.

**Comment by cjh1** [comment]
@saransh13 Let merge this  :+1:

**Pull request merged**
