### PR TITLE
Build package in container

### PR DESCRIPTION
**Pull request by cjh1**
This PR moves the build of the package into a older Linux container. This ensure that we build with an old version of glibc so the package will work on older distros as well. @joelvbernier this should resolve the issue your collaborator is seeing.

### CODE REVIEW

**Comment by cjh1** [comment]
@psavery When this builds can you try the package produced for me, to check it works on your machine?

**Comment by psavery** [comment]
Will do... on Monday :slightly_smiling_face:

**Comment by joelvbernier** [comment]
This won't create any problems with current linux systems, correct?  If it is a pain to try to support older linux distros (like RHEL6), then we can just punt on this.

**Comment by cjh1** [comment]
It won't, @psavery is going to do a final test for me.

**Comment by psavery** [comment]
My review is not valuable enough to merit a merge...

**Comment by cjh1** [comment]
@joelvbernier I am going to go ahead and merge this if that is ok?

**Pull request merged**
