### PR TITLE
Add PyYAML Loader and Dumper to handle numpy.ndarray

### LINKED ISSUE #28: Handling array-like panel buffers (masks) in instrument config write
The current output method `instrument.HEDMInstrument().write_config()` is _not_ appropriate if the panel buffers are array-like.  There are two possible fixes, and perhaps we should implement both.
1. Add an HDF5 instrument config format, and store the buffer as a dataset (numpy ndarray)
2. In the case of array-like panel buffer, add a trigger in the YAML output to load buffer from a flat npy file that gets auto-generated.

Thoughts @cryos @psavery @cjh1 @donald-e-boyce ?

### PR DESCRIPTION
**Pull request by cjh1**
This is to support numpy array's in the instrument panel buffer.

Fixes #28

### CODE REVIEW

**Comment by joelvbernier** [comment]
@cjh1 -- any idea why the windows packaging test failed?

**Comment by cjh1** [comment]
@joelvbernier I saw that yesterday, I tried restart it a could of times, no dice, I will dig into it some more ...

**Comment by cjh1** [comment]
@joelvbernier A four restart did it!

**Comment by joelvbernier** [comment]
@cjh1 -- do you have an example on how to use this?

**Comment by cjh1** [comment]
@joelvbernier  So to dump out a dict that contains a numpy.ndarray, you would use the following:

```python
yaml.dump(d, stream=f, Dumper=NumPyIncludeDumper)
```

This will serialize the numpy array to a file relative to the YAML doc. Inside the YAML doc you will find the array replaced with something like `!include <numpy_file_path>`.

To load it back in:

```python
 yaml.load(f, Loader=NumPyIncludeLoader)
```

**Comment by joelvbernier** [comment]
Ok, I will try it out!

**Pull request merged**
