### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by joelvbernier**
Just to be safe, pin fabio version to >=0.11 (on conda-forge)

### CODE REVIEW

**Comment by joelvbernier** [comment]
@psavery -- should we do anything in setup.py as well?

**Comment by psavery** [comment]
@joelvbernier We can do the same kind of thing if you'd like.

**Review by joelvbernier — COMMENTED** [review]
I think this is ready.

**Comment by joelvbernier** [comment]
I'll merge this upon receiving your blessing @psavery

**Pull request merged**
